#!/bin/sh

cd ${0%/*}/..
TOPDIR=${PWD}
LOGDIR=${TOPDIR}/logs
TESTSUITE_DIR=${TOPDIR}/testsuite

builders=`cat ${LOGDIR}/stage1/results-stage1.txt | cut -f1 -d' ' | sort | uniq`
targets=`cat ${LOGDIR}/stage1/results-stage1.txt | cut -f2 -d' ' | sort | uniq`
output="${LOGDIR}/stage1/stage1-results.shtml"
body_only=1

# create target -> build symlinks
for t in ${targets}; do
  mkdir -p ${LOGDIR}/stage1/per-target/${t}
  for b in ${builders}; do
    [ ! -L ${LOGDIR}/stage1/per-target/${t}/${b} ] && ln -s ../../${b}/${t} ${LOGDIR}/stage1/per-target/${t}/${b}
  done
done

# generate redirect from per-target to results
echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
  <head>
    <title>Deli redirect</title>
    <META HTTP-EQUIV="Refresh" CONTENT="0; URL=../">
  </head>
  <body>
  </body>
</html>
' > ${LOGDIR}/stage1/per-target/index.html

# generate page with stage1 results
> ${output}

if [ $body_only -eq 0 ]; then
echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>
      Fedora Bootstrap - Results
    </title>
    <style type="text/css">
      <!--
	table a {
	  text-decoration: none;
	  display: block;
	  text-align: center;
	  width: 100%;
	  color: black;
	}
	h3 {
	  text-decoration: underline;
	}
	h4 {
	  text-decoration: underline;
	}
	td.ok {
	  background-color: #30DF30;
	}
	td.missing {
	  background-color: #7070FF;
	}
	td.failed {
	  background-color: #FF4040;
	}
	td.skipped {
	  background-color: #AAAAAA;
	}
      -->
    </style>
  </head>
  <body>' >> ${output}
fi

echo '    <h3><u>STAGE1 Results</u></h3>
    <table>
      <tr>
	<th>B\T</th>' >> ${output}
for t in ${targets}; do
  echo "	<th><a href='per-target/${t}/'>&nbsp;${t}</a></th>" >> ${output}
done
echo "      </tr>" >> ${output}
for b in ${builders}; do
  echo "      <tr>" >> ${output}
  echo "	<th><a href='${b}/'>&nbsp;${b}</a></th>" >> ${output}
  for t in ${targets}; do
    result=`cat ${LOGDIR}/stage1/results-stage1.txt | grep "^${b} ${t} " | cut -f3 -d' '`
    cat ${LOGDIR}/stage1/results-stage1.txt | grep "^${b} ${t} " &> /dev/null
    missing=$?
    if [ ${missing} = 0 ]; then
      if [ "${result}" == "*OK*" ]; then
        echo "	<td class='ok'><a href='${b}/${t}/'>&nbsp;</a></td>" >> ${output}
      elif [ "${result}" == "*MISSING*" ]; then
        echo "	<td class='missing'></td>" >> ${output}
      else
        echo "	<td class='failed'><a href='${b}/${t}/${result}.log'>${result}</a></td>" >> ${output}
      fi
    else
      echo "	<td class='missing'></td>" >> ${output}
    fi
  done
  echo "      </tr>" >> ${output}
done
echo '    </table>
    <br>
    <u>Table legend:</u>
    <table>
      <tr>
	<td>B</td><td>&nbsp;&nbsp; BUILD (--build=)</td>
      </tr>
      <tr>
	<td>T</td><td>&nbsp;&nbsp; TARGET (--host=,--target=)</td>
      </tr>
      <tr>
	<td class="ok"></td><td>&nbsp;&nbsp; working combination of BUILD & TARGET</td>
      </tr>
      <tr>
	<td class="failed">failing recipe</td><td>&nbsp;&nbsp; failing combination of BUILD & TARGET</td>
      </tr>
      <tr>
	<td class="missing"></td><td>&nbsp;&nbsp; result missing</td>
      </tr>
    </table>' >> ${output}

# Filelist diffs table
echo '    <br>
    <h4>Filelist diffs</h4>
    <table>
      <tr>
	<th>B1xB2\T</th>' >> ${output}
for t in ${targets}; do
  echo "	<th><a href='diffs/${t}/'>&nbsp;${t}</a></th>" >> ${output}
done
echo "      </tr>" >> ${output}

# Sort filelists
for b in ${builders}; do
  for t in ${targets}; do
    filelist="${LOGDIR}/stage1/${b}/${t}/filelist.txt"
    [ -f ${filelist} ] && cat ${filelist} | sort > ${filelist}.sorted && mv ${filelist} ${filelist}.unsorted && mv ${filelist}.sorted ${filelist} && rm -f ${filelist}.unsorted
  done
done

builder_cnt=`echo ${builders} | wc -w`
for idx1 in `seq 1 $((builder_cnt-1))`; do
  for idx2 in `seq $((idx1+1)) ${builder_cnt}`; do
    b1=`echo ${builders} | cut -d' ' -f${idx1}`
    b2=`echo ${builders} | cut -d' ' -f${idx2}`
    echo "      <tr>" >> ${output}
    echo "	<th>${b1} ${b2}</th>" >> ${output}
    for t in ${targets}; do
      result1=`cat ${LOGDIR}/stage1/results-stage1.txt | grep "^${b1} ${t} " | cut -f3 -d' '`
      result2=`cat ${LOGDIR}/stage1/results-stage1.txt | grep "^${b2} ${t} " | cut -f3 -d' '`
      if [ ! "${result1}" = "*OK*" ] || [ ! "${result2}" = "*OK*" ]; then
	echo "	<td class='skipped'></td>" >> ${output}
	continue
      fi
      filelist1="stage1/${b1}/${t}/filelist.txt"
      filelist2="stage1/${b2}/${t}/filelist.txt"
      if [ -f ${LOGDIR}/${filelist1} ] && [ -f ${LOGDIR}/${filelist2} ]; then
        mkdir -p ${LOGDIR}/stage1/diffs/${t}
	(cd ${LOGDIR} && diff -Naur ${filelist1} ${filelist2} > ${LOGDIR}/stage1/diffs/${t}/${b1}-${b2}.txt)
	if [ $? -eq 0 ]; then
	  echo "	<td class='ok'></td>" >> ${output}
	else
	  echo "	<td class='failed'><a href='diffs/${t}/${b1}-${b2}.txt'>diff</a></td>" >> ${output}
	fi
      else
	echo "	<td class='missing'></td>" >> ${output}
      fi
    done
    echo "      </tr>" >> ${output}
  done
done
echo '    </table>
    <br>
    <u>Table legend:</u>
    <table>
      <tr>
	<td>B1, B2</td><td>&nbsp;&nbsp; BUILD (--build=)</td>
      </tr>
      <tr>
	<td>T</td><td>&nbsp;&nbsp; TARGET (--host=,--target=)</td>
      </tr>
      <tr>
	<td class="ok"></td><td>&nbsp;&nbsp; empty diff</td>
      </tr>
      <tr>
	<td class="failed"><center>diff</center></td><td>&nbsp;&nbsp; non-empty diff</td>
      </tr>
      <tr>
	<td class="missing"></td><td>&nbsp;&nbsp; filelist missing</td>
      </tr>
      <tr>
	<td class="skipped"></td><td>&nbsp;&nbsp; skipped (incomplete build)</td>
      </tr>
    </table>' >> ${output}

if [ $body_only -eq 0 ]; then
echo '    <br>
  </body>
</html>' >> ${output}
fi
