#!/bin/sh

pkg_installer='yum -y install'
STAGE1_TARGET_ARCH_LIST='x86_64 i686 aarch64 armv7hl ppc64le ppc64 s390x'

cd ${0%/*}/..
TOPDIR=${PWD}
LOGDIR=${TOPDIR}/logs
TESTSUITE_DIR=${TOPDIR}/testsuite
SCRIPTS_DIR=${TOPDIR}/scripts

# run in a background
if [ "$1" == "--screen" ]; then
  shift
  command="${TESTSUITE_DIR}/run-stage1 $@"
  screen -d -m -L $command
  exit 0
fi

TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S`

# download SRPMs
mkdir -p SRPMs
mkdir -p SRPMlocal
mkdir -p NOARCHs
cd SRPMs
${SCRIPTS_DIR}/download-stage1-srpms
${SCRIPTS_DIR}/download-stage2-srpms
cd ../NOARCHs
${SCRIPTS_DIR}/download-stage1-noarch
cd ..

for arch in $STAGE1_TARGET_ARCH_LIST; do

  echo ""
  echo "==== Building stage1 for $arch ===="

  # clean leftovers from the previous run
  rm -rf builds done install rootfs rpmbuild

  # set the TARGET
  sed -i "s|^TARGET_ARCH=.*|TARGET_ARCH=${arch}|" stage1

  ./stage1

  mkdir -p ${LOGDIR}/$arch
  mv ${LOGDIR}/*.log ${LOGDIR}/$arch/

  (cd rootfs ; find > ${LOGDIR}/$arch/filelist.txt)

  mv done done.${arch}
  mv install install.${arch}
  mv rootfs rootfs.${arch}
done

# if executed remotely, then make a package containing all logs (sleep required for flushing the screen log)
[ -f screenlog.0 ] && sleep 11 && mv screenlog.0 ${LOGDIR}/screenlog-stage1.txt && cd logs && tar czf logs-stage1.tgz * && mv logs-stage1.tgz ../
