#!/bin/sh
downloader="yumdownloader --releasever=21 --source --enablerepo=updates-testing-source "

$downloader ncurses \
	    m4 \
	    readline \
	    nspr \
	    sqlite \
	    gdbm \
	    libdb4 \
	    perl \
	    popt \
	    nss-util \
	    nss-softokn \
	    nss \
	    file \
	    libarchive \
	    redhat-rpm-config \
	    rpm \
	    autoconf \
	    lua \
	    libtool \
	    pkgconfig \
	    gettext \
	    bison
